### ISSUE TITLE
GDD

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#1]
- [ ] Actualizar fotos.
- [x] Cambios de historia
- [ ] Desarrollar mecánicas
- [x] Desarrollar Plot points
- [ ] Personajes
- [ ] Interfaz
- [ ] Movimientos (Controles)
- [ ] Diseño nivel
- [ ] Referencias (Música, Juegos, etc...)
- [ ] Alcance y publico objetivo

**Comment by iuvissito** [comment]
cambios historia y lot points realizados ,muevo el apartado gdd a fila en progreso

**Comment by vcalzadaga** [comment]
Esto está fatal!!! Cada tarea tiene que ser un Issue diferente. Tampoco lo habéis asociado al Millestone. 

Lo vemos hoy en clase
