### ISSUE TITLE
Bestiario

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#10]

**Comment by vilkiin** [comment]
Bestiario
-Jungla:
![Mono](https://user-images.githubusercontent.com/79110145/140827059-61c311ca-b339-4ff4-a6fb-0b9245746897.png)

Este es un enemigo ágil que se encontrará en zonas elevadas y lanzará plátanos, pero ten cuidado cuando se le acaben ya que echará a correr a por ti.


![Serpiente](https://user-images.githubusercontent.com/79110145/140827039-e58af545-657a-4571-aadb-e3986e1923cb.png)

Es un enemigo básico que te cortara en paso por zonas del suelo de la jungla y gracias a sus patas en capaz
de llegar más lejos con la mordida.

![Rinoceronte](https://user-images.githubusercontent.com/79110145/140827015-99913bf5-9e80-4d6b-948e-83ab06d703b5.png)

Este se trata de un enemigo pesado que aguantara una gran cantidad de golpes y además de eso el único peligro que tiene no es solo el cuerno.

-Desierto: 
![Avestruz](https://user-images.githubusercontent.com/79110145/140826988-f5072e1c-9ea1-438b-a017-12d0e044703a.png)

Realmente más que como enemigo cuenta como obstáculo, su única función es meter la cabeza en el suelo y poner los pinchos de punta asique te las tendrás que apañar para sortearlo.


![Escorpion](https://user-images.githubusercontent.com/79110145/140826954-bb187d80-f21e-4b67-9ce7-747330a58e43.png)

Este enemigo es un habitante de las cuevas y, aunque no sea el animal más grande, siempre genera problemas con las bolas de veneno de sus aguijones. Si estos te envenenan... corre.


![Camello](https://user-images.githubusercontent.com/79110145/140826902-71f6964c-854e-4ed8-9d3c-84f4e4dcc22a.png)

Que más decir, es un camello táctico, tiene pollos y encima es táctico.
