### ISSUE TITLE
Controles

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#11]

**Comment by iuvissito** [comment]
![controkes gamepad](https://user-images.githubusercontent.com/79115832/141222599-2a7669cf-8e13-4750-9cb1-2ad5c533938f.png)
imagen controles gamepad

**Comment by iuvissito** [comment]
![controles teclado y ratón](https://user-images.githubusercontent.com/79115832/141358891-e9bec7b2-a849-4df3-aca8-b1c1a92784a5.png)
 imagen controles teclado
