### ISSUE TITLE
Plataforma

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#12]

**Comment by iuvissito** [comment]
1.7 PLATAFORMAS

Las plataformas en principio pensadas para este juego ,tenemos pensado para pc y consola , hábiles para todas las consolas, que no estaría restringido a ninguna aunque estamos valorando intentar a futuro que se pueda jugar en dispositivos móviles,como tabletas y teléfonos ,de tal forma que desde cualquier dispositivo hábil para el jugar ,nuestro pequeño Flash te enamore
