### ISSUE TITLE
Equipo humano

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#14]

**Comment by Milena1799** [comment]
Equipo humano realizado, cada uno hemos escrito algo sobre nosotros y hemos puesto a lo que nos dedicaremos en el juego.
Somos Lazy Claws, nuestro equipo:
Ruben Alia Maria: Diseño de niveles, texturizado y animación.
Victor Fernández de la Torre: Modelado y texturizado
Jairo Piña Salas: Programación, Música y animación
Milena Guerrero: Estilo visual y Diseño de niveles
Jorge Díaz Fernández: Programación, interfaz y animación

MILENA GUERRERO
Soy estudiante de un grado superior de Animación 3D y videojuegos, tengo un grado medio de Sistemas Microinformáticos y redes.
Me gustaría dedicarme a algo relacionado con la animación ya que me apasiona realizar aquello que tengo en mi imaginación.
En mi tiempo libre me apasiona ver series de animación y películas.

**Comment by vilkiin** [comment]
JORGE DÍAZ FERNÁNDEZ
Soy Jorge Díaz Fernández, tengo 22 años y estudio el Grado Superior de Animación 3D, juegos y entornos interactivos. Me gustaría dedicarme a crear videojuegos o modelar objetos.
En mi tiempo libre juego a videojuegos, ver películas y series  y jugar al tenis y al fútbol con mis amigos.

**Comment by iuvissito** [comment]
RUBEN ALIA
Hey ,buenas soy Rubén Alía ,mis amigos me conocen como iuv , tengo la asombrosa edad de 22 años ,estoy muy viejo
Actualmente estoy estudiando en el CIFP Jose luis Garci, animación 3d ,tengo algún cursillo por ahí de doblaje,vfx y modelado 3d ,tambien tengo un grado superior de REA
En mi tiempo libre me gusta perderme por algún lado, me gusta inventarme como 1000 historias en mi cabeza ,aunque no las escriba ,lo tengo pendiente , escribir poemas, jugar videojuegos ,aunque ahora no tengo tiempo :(((,ver series y/o películas y analizarlas.
En un futuro me gustaría tener mi propio podcast ,que por cierto está en proceso, presentar algún corto propio a festivales ,modelar ,animar y doblar mi propio personaje ,y este es un breve resumen sobre mi 
ADIOOOSSSS

**Comment by Jairop310** [comment]
Soy Jairo Piña, tengo 19 años y estudió la FP de Animación 3D, juegos y entornos interactivos.
En un futuro me gustaría dedicarme profesionalmente a la programación orientada a Videojuegos aunque dedicarme a la texturización tampoco me desagrada.
Durante mi tiempo libre me gusta ver series de anime y jugar videojuegos, aunque también disfruto pasando tiempo con mi familia y amigos.

**Comment by Apodomorata** [comment]
VICTOR FERNANDEZ
Hola muy buenas, me llamo Víctor Fernández, tengo 20 años y estoy estudiando una FP de Animación 3D y en un futuro me gustaría dedicarme profesionalmente en ser modelador para videojuegos. En mi tiempo libre  me gusta pasarlo con mis amigos, jugar a videojuegos y ver series, o películas, de animación.
