### ISSUE TITLE
Dinámicas

### ISSUE THREAD

**Issue by Milena1799** [CIFP-Jose-luis-Garci/LazyClawns#15]

**Comment by Apodomorata** [comment]
DINÁMICAS  
El juego busca aportar al jugador una experiencia distinta, buscando un tono humorístico e intentando generar al jugador un poco de curiosidad.
El objetivo es  que los jugadores tengan ganas de seguir viendo nuevas criaturas y combinaciones de animales, apoyándonos en fomentar la exploración, para que puedan obtener los datos de los coleccionables sobre animales.
