### ISSUE TITLE
Características principales

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#17]

**Comment by vilkiin** [comment]
Características principales:
Una de las características principales es el aprendizaje del jugador respecto a algunos animales que van apareciendo en los niveles. Otra de las características es que es un juego 2.5D, personajes en 2D y entorno tridimensional. También tendrá un combate frenético pero sin ser demasiado para que siga siendo apetecible para un público casual. Además de tener un sentido del humor muy importante para la trama.

**Comment by vcalzadaga** [comment]
muy bien
