### ISSUE TITLE
Concepto del juego

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#18]

**Comment by vilkiin** [comment]
Concepto juego: 
Nuestro protagonista, un perezoso, no se encuentra cómodo tal como es, y al haber crecido con unos leopardos ama la velocidad, por lo que se aventura a buscar el legendario libro de la genética para poder cambiar sus habilidades. Descubre que el malvado salmón Salomón robó el libro y está haciendo uso de él para formar un ejército, que nuestro protagonista tendrá que vencer para lograr su objetivo.
