### ISSUE TITLE
Flujo del juego

### ISSUE THREAD

**Issue by Milena1799** [CIFP-Jose-luis-Garci/LazyClawns#19]

**Comment by Apodomorata** [comment]
FLUJO DEL JUEGO  
 	Al ser un juego lineal tiene pocas desviaciones de la historia y de nivel, por ejemplo, podrías tomarte tu tiempo en un nivel para encontrar sitios ocultos con coleccionables.

**Comment by Apodomorata** [comment]
![Sin_titulo](https://user-images.githubusercontent.com/91078700/141164080-563e898e-7e5f-4da9-ae94-e1d287bb8e49.jpg)
