### ISSUE TITLE
Estilo visual

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#20]

**Comment by Milena1799** [comment]
El estilo visual de nuestro juego:
El juego tendrá un estilo cartoon el cual ayudará tanto a la dinámica del juego como a la historia, ya que nuestros personajes serán animales alterados genéticamente.
Nuestros personajes serán 2D y nuestros escenarios en 3D.

**Comment by vcalzadaga** [comment]
En el apartado de estilo visual había más puntos por tratar: 
o Concept art
o Diseño de personajes
o Diseño de escenarios
o Objetos, armas, power up, coleccionables…
o Otros: mapas, botones…

No sé si lo habéis incluido en otro issue, me parece que no

**Comment by Jairop310** [comment]
Se encuentras en otros issue repartido en cada apartad.
