### ISSUE TITLE
Personajes

### ISSUE THREAD

**Issue by Milena1799** [CIFP-Jose-luis-Garci/LazyClawns#21]

**Comment by Jairop310** [comment]
Flash el Perezoso:
Flash, nuestro protagonista es un joven perezoso que habita en la jungla junto a su familia adoptiva, los leopardos, con los que pasó toda su infancia. Nuestro protagonista es un perezoso un tanto peculiar ya que nació de un huevo, por lo tanto, se desconoce de su familia real. Físicamente hablando, nuestro perezoso, Flash, dada su corta edad no es muy grande ni muy alto ni tiene el cuerpo muy desarrollado, pero, a diferencia del resto de los de su especie, dado a que este se ha criado con leopardos, ha desarrollado una gran velocidad, una capacidad de salto y de escalada fuera de lo común y una agilidad fuera de lo normal en un perezoso, ya que este sabe correr, trepar, nadar y saltar muy alto. Hablando ahora de actitud y personalidad, Flash es un perezoso muy activo y alegre, su mayor entretenimiento es jugar con otros animales de la jungla que, por lo normal, serían más ágiles que él pero este es capaz de seguirles el ritmo hasta a los monos más rápidos, pero, por otro lado, también ha desarrollado un instinto salvaje heredado de los leopardos, pero ya que este no cazaba para comer, lo que hacía era organizar peleas con otros animales de la jungla y, por lo común, todos más grandes y fuertes que él, solo por diversión y para ver sus fuerzas, ha llegado a combatir con rinocerontes y elefantes. Ahora hablando de la jugabilidad en el juego, la manera en la que flash ataca para derrotar enemigos, no es con armas ni artilugios ni nada parecido ya que la historia se desarrolla en un entorno salvaje por lo que solo atacará con las garras, eso sí, tendrá varios ataques distintos y combos que aumentaran su poder como por ejemplo lanzar las garras y atraer al enemigo. En cuanto a debilidades como tal no tiene ninguna en específico, no tiene ningún punto débil ni ningún lado desde el que si le dan le hagan daño aumentado.

**Comment by Jairop310** [comment]
Salomón el Salmón:
Salomón, desde que nació era un salmón especial, más pequeño de lo habitual, al ser tan pequeño y débil le costó bajar ,río abajo ,tuvo que ser ayudado por los demás salmones, incluso ya pasado un tiempo cuando remontaban de vez en cuando el río ,no podía hacerlo solo ,ni siquiera en los tramos más fáciles, le eran imposibles ,sin ayuda, lo que más de una vez les costó más de un disgusto, a él y sus compañeros ,debido a esto ,llegó a ser el flanco de burlas de los demás salmones ,para intentar remediar esto se empezaría a someter a un intenso entrenamiento, por su cuenta ,un día por pura casualidad, encontró un libro, no tardaría en descubrir que era el libro de la genética y su poder, lo usaría par a aumenta en fuerza y tamaño ,además de agregarse alas para volar ,la capacidad de respirar fuera del agua y colmillos, actualmente vive en la montaña más alta ,con el río más bravo como único acceso, desde donde gobierna el reino animal, con mano de hierro y cambiando la genética a su antojo.
