### ISSUE TITLE
Inventario

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#22]

**Comment by Jairop310** [comment]
El inventario que utilizaremos y como se navegara en el.
 El inventario será accesible en todo momento durante la aventura, estar compuesto de tres apartados: Mochila, Bestiario y coleccionables, en la mochila podrás revisar la cantidad de objetos que posees y colocarlos en los botones para uso más rápido también podrás revisar los objetos para la solución de puzles, en el Bestiario encontrarás información valiosa de los enemigos como cuál es su debilidad y cuales son sus resistencias entre otras, finalmente en los coleccionables podrás revisar todos los que hayas recogido durante la aventura. También hay un selector de que elemento tienes en ese momento dándote 5 opciones de las cuales solo podrás elegir uno de ellos.

**Comment by vcalzadaga** [comment]
Echo de menos alguna información más. Por ejemplo:

- ¿El bestiario contiene información de todos los enemigos del juego? O se van a ir añadiendo a la vez que el personaje progresa de niveles
- "en la mochila podrás revisar la cantidad de objetos que posees y colocarlos en los botones para uso más rápido". Creo que sé lo que queréis decir, pero explicadlo un poco mejor
- Cuando accedes al inventario ¿el juego se pausa?, ¿el inventario se despliega? ¿puedes acceder a la vez que sigues jugando?

**Comment by Jairop310** [comment]
Inventario Actualizado:
El inventario será accesible en todo momento durante la aventura, estará compuesto de tres apartados: Mochila, Bestiario y coleccionables.
En la mochila podrás revisar la cantidad de objetos que posees y colocarlos en los botones para uso más rápido, haciendo que sean accesibles de manera más sencilla desde teclas o botones específicos también podrás revisar los objetos para la solución de puzles. 
En el Bestiario encontrarás información valiosa de los enemigos como cuál es su debilidad y cuales son sus resistencias entre otras, esta información se irá desbloqueando a medida de que aparecen los enemigos, 
Finalmente en los coleccionables podrás revisar todos los que hayas recogido durante la aventura.
Cuando se acceda al inventario el juego se pausa dándote todo el tiempo necesario para organizarlo todo.
También hay un selector de que elemento tienes en ese momento dándote 5 opciones de las cuales solo podrás elegir uno de ellos, en este menú el juego no se parará si no que se ralentizará dándote tiempo a seleccionar pero que no sea tiempo ilimitado.
