### ISSUE TITLE
Alcance

### ISSUE THREAD

**Issue by vcalzadaga** [CIFP-Jose-luis-Garci/LazyClawns#23]

**Comment by Jairop310** [comment]
Nuestra intención al terminar el  curso es tener terminado el primer nivel que servirá a la vez como tutorial y presentación del juego, al igual que Sprite de los enemigos. Tendremos una habilidad desarrollada y el combate sin ellas, además  de los objetos y las interfaces que se usarán durante todo el nivel. Y el Sprite del jefe final del juego para la presentación.
