### ISSUE TITLE
Referencias

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#24]

**Comment by Milena1799** [comment]
4.3 Referencias

Referencias para niveles y juga
![148131981855011](https://user-images.githubusercontent.com/90465340/141176375-9dee4207-1ab1-427f-bb73-94890c93a5b0.png)
dores
![esqueleto-rey-salmC3B3n-dibujo-eps-vectorial_csp69870248](https://user-images.githubusercontent.com/90465340/141176382-26fa6987-8465-4def-a465-81ad7186cfc9.png)

![46723691-ilustraciC3B3n-del-salmC3B3n-rojo-o-salmC3B3n-rojo-](https://user-images.githubusercontent.com/90465340/141175815-1c65612b-b1d4-4061-8c4b-cdb97ceab769.png)
:
![gratis-png-robot-escorpion-humanoide-dibujo-escorpion](https://user-images.githubusercontent.com/90465340/141176286-d35f606d-9172-4b63-b1dd-1da555df90c6.png)
![istockphoto-1208372699-170667a](https://user-images.githubusercontent.com/90465340/141176306-45f73cc2-f669-4155-8a3f-0d9a91642798.jpg)
![paisaje-desierto-dia-cactus_23-2148276562](https://user-images.githubusercontent.com/90465340/141176313-d8a813ef-757c-41df-a1fa-1cb96821125c.jpg)
![istockphoto-1130320273-612x612](https://user-images.githubusercontent.com/90465340/141176319-dcbc4302-a4a6-4f46-b3b6-7cafa7b79f87.jpg)
![unnamed](https://user-images.githubusercontent.com/90465340/141176322-57bd8df0-ce93-49ba-a855-b69104348987.jpg)
![ninja-perezoso-poster](https://user-images.githubusercontent.com/90465340/141176326-b24f3340-e7cd-4689-837b-486e24cb45cc.png)
![3baa3804ffe1a9f36609c0827fac6745](https://user-images.githubusercontent.com/90465340/141176340-174183f8-8307-48c9-b4ad-4aeff66384b9.jpg)
![46723691-ilustraciC3B3n-del-salmC3B3n-rojo-o-salmC3B3n-rojo-](https://user-images.githubusercontent.com/90465340/141176358-da6c3d32-6ce3-44ea-9767-7d8cc1776941.png)

**Comment by Milena1799** [comment]
Referencias de personajes y escenarios
![paisaje-desierto-dia-cactus_23-2148276562](https://user-images.githubusercontent.com/90465340/141177794-3d3cd030-d79d-4f7a-9fc0-e4a262d67ebc.jpg)
![unnamed](https://user-images.githubusercontent.com/90465340/141177800-759eb215-bac2-42f1-81ea-63975d96742d.jpg)
![mutant-creatures-half-animal-and-human-vector-31352254](https://user-images.githubusercontent.com/90465340/141177804-d3951456-b3e9-4094-a914-6931f09aff28.jpg)
![istockphoto-491375864-612x612](https://user-images.githubusercontent.com/90465340/141177818-f0caa53a-81d1-4c30-bc5c-952051bcc941.jpg)
![kisspng-salmon-clip-art-5b379049e662a9 9631646715303680739437](https://user-images.githubusercontent.com/90465340/141177820-b8a03d81-d37d-4e2b-9909-78759c9a3715.jpg)
![ninja-perezoso-poster](https://user-images.githubusercontent.com/90465340/141177825-3d66eb52-673a-4fa8-b93e-6ae2a4e22a18.png)
![148131981855011](https://user-images.githubusercontent.com/90465340/141177839-1dbe4759-65b3-4423-ba32-07ab01ccb87c.png)
![istockphoto-1130320273-612x612](https://user-images.githubusercontent.com/90465340/141177850-a1a6c060-f4bc-41fd-8581-33297df9c2ed.jpg)
![istockphoto-1208372699-170667a](https://user-images.githubusercontent.com/90465340/141177854-03e0916a-1782-4985-b8d5-178e4aaaa39b.jpg)
