### ISSUE TITLE
Menú principal

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#25]

**Comment by Milena1799** [comment]
3.1 Menú principal
El menú principal consta con un estilo divertido.
 En el veremos la interfaz la cual consta de los siguientes botones: 
-Jugar: Podremos acceder a nuestro juego
-Configuración: Accederemos al sonido, a los controles del juego, etc.
-Libro de genética: En él podremos encontrar la historia de los personajes como su genética y los coleccionables que hemos encontrado.
-Créditos: Quienes han hecho el juego y sus papeles.
-Salir: Podrás cerrar el juego.
Algo diferente de nuestro videojuego será que encontraremos el personaje de distinta manera según vaya avanzando el videojuego ya que nuestro personaje va creciendo
![libro_selva](https://user-images.githubusercontent.com/90465340/141345289-9dc418f5-3356-43f0-b629-f0568f3d5018.png)
![fondo_menu](https://user-images.githubusercontent.com/90465340/141345301-d2f9407e-35de-4be2-9ae1-af2b30f05b97.png)
![ninja_fondo1](https://user-images.githubusercontent.com/90465340/141345319-2b924b1f-9fb8-42ea-bb1e-7384a1db79d0.png)
.
