### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#26]

**Comment by Jairop310** [comment]
En el HUD podemos encontrar diferentes objetos que nos acompañarán en todo momento durante la aventura. 
Entre ellos están la información del jugador, arriba a la izquierda, en ella se nos mostrará cuántas vidas le quedan y cuanto daño ha recibido hasta el momento. Está decorado con un tocado especial en cada nivel, en este caso sería el de la jungla, abajo a la derecha tenemos un acceso al inventario para la gente que utiliza teclado y ratón, mientras que abajo izquierda está el mapa y el bestiario.

**Comment by Jairop310** [comment]
![HUD](https://user-images.githubusercontent.com/90465353/140831009-10885650-1d72-4fe5-898f-8b80a7085a57.png)
Imagen de ejemplo del HUB

**Comment by vcalzadaga** [comment]
El marcador de vida muy chulo
