### ISSUE TITLE
Grafica de dificultad

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#27]

**Comment by iuvissito** [comment]
![perecoso - copia](https://user-images.githubusercontent.com/79115832/141215821-ea6ae36a-d714-473f-9ac9-e84d251a51f2.png)
![perecoso fondo blanco](https://user-images.githubusercontent.com/79115832/141215829-a4a3e241-7399-4976-b015-bd735712510c.png)

subo 2 imagenes una sin fondo otra con fondo

**Comment by iuvissito** [comment]
en esta grafica vemos la dificultad de nuestro juego avanza progresivamente de manera exponencial según avance el juego vemos de amarillo la historia 
de rojo dificultad
de azul habilidad enemigos
de verde habilidad personaje

**Comment by iuvissito** [comment]
![grafica perezoso](https://user-images.githubusercontent.com/79115832/141220747-5a6bf2fb-9e2d-4792-ab26-143def4c2367.png)
