### ISSUE TITLE
Diagrama de Gantt

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#35]

**Comment by Jairop310** [comment]
[Diagrama de Grantt - Hoja 1.pdf](https://github.com/CIFP-Jose-luis-Garci/LazyClawns/files/7722060/Diagrama.de.Grantt.-.Hoja.1.pdf)

**Comment by Jairop310** [comment]
La hoja de calculo ya esta hecha

**Comment by Milena1799** [comment]
Archivo png
![GANTTPROJECT](https://user-images.githubusercontent.com/90465340/146250222-50fb1d05-0bf0-4073-aaaa-a1dc51a8226f.png)
