### ISSUE TITLE
Flujo de Trabajo

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#37]

**Comment by Apodomorata** [comment]
Gestion de recursos + toma de decisiones en la empresa:

Dentro de la empresa se utilizarán programas de organización de información como Github. En él los trabajadores irán subiendo sus trabajos. Cada director de departamento irá revisando el trabajo de sus subordinados, de esta manera se hará un seguimiento del flujo de trabajo y de la calidad del mismo.

Se seguirá una jerarquía, estipulada previamente, en la que habrá un jefe de departamento. En él recaerá la toma de decisiones y buscará realizar con éxito las tareas planificadas en la fase de preproducción.

**Comment by iuvissito** [comment]
Metodo de trabajo + reuniones :
Vamos a trabajar de una manera online  y presencial ,cada uno trabajara desde su casa con cada tarea asignada ,ya sean pequeñas ,similar a una forma de trabajo de modo scrum ,de forma que vamos a poder hacer partes del proceso independientes y luego ,en las reuniones,que serán los puntos de puesta en común ,algunas serán a través de aplicaciones de llamada como Discord ,o presencial cuando podamos reunirnos, aprovechando el tiempo en clase o incluso recreos ,donde pondremos en común el proceso y pondremos en común ,los problemas y el desarrollo que necesiten la presencia de todos ,como los hitos.

**Comment by vilkiin** [comment]
![Añadir un subtítulo](https://user-images.githubusercontent.com/79110145/149207785-0bfa3e08-dfe0-4720-ae94-26c4c1c9faa7.png)
