### ISSUE TITLE
Financiación

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#39]

**Comment by Milena1799** [comment]
Financiación o Monetización

Financiación 

Nuestra financiación la queremos obtener por parte del ministerio de industria.
Como con el Organismo ENISA, con su financiación podríamos obtener ayudas, ya que las proporcionan a emprendedores para empresas de videojuegos.

También utilizaremos para financiarnos la financiación propia, los concursos y certámenes junto con las campañas de Crowdfounding.

Nos pondremos en contacto con una empresa Publisher para que nos financie nuestro proyecto obteniendo a cambio un porcentaje de ingresos gracias a la comercialización del videojuego.

Monetización

Obtendremos beneficios por parte de merchandising de nuestro videojuego, como camisetas con nuestros personajes, peluches, tazas…
Obtendremos ingresos a través de publicidad que verán los jugadores.
También utilizaremos microtransacciones donde nuestros jugadores podrán obtener objetos virtuales mediante micropagos de nuestro videojuego.
