### ISSUE TITLE
Historia

### ISSUE THREAD

**Issue by Milena1799** [CIFP-Jose-luis-Garci/LazyClawns#4]

**Comment by iuvissito** [comment]
Historia;  
 	Todo comienza con un huevo de oso perezoso y una familia de leopardos que lo acechan desde las ramas de un árbol, ese mismo día una ráfaga de viento hace que el huevo caiga y con suerte no se rompe en la caída, pero el sonido que produce despierta a los leopardos que ya se estaban quedando dormidos de tanto esperar.  
 	Los leopardos, al bajar del árbol ven que el caparazón está roto, así que la curiosidad les hace investigar el huevo, al cabo de unos segundos, uno de los leopardos que está olfateando el huevo, recibe una patada prominente del huevo ¡¡¡ Era nuestro protagonista!!! Flash dio su primer paso, en la cara del leopardo y al instante sacó el otro pie, nuestro protagonista ya podía andar, aunque no fuera la mayor cualidad de su raza. Flash no salió del cascarón hasta pasados 6 días, de tal manera que por culpa del golpe solo pudo sacar las patas y andar durante este tiempo. Cuando sale del huevo, ve por primera vez a su familia de leopardos y con el tiempo se da cuenta que quieres ser tan rápido como ellos, por lo que decide comenzar una aventura para encontrar el libro antiguo de la genética y así poder cambiar su lentitud a cambio de la velocidad de sus padres adoptivos. 
 	En el inicio de su aventura los leopardos enseñan a nuestro perezoso a cómo moverse y a correr (mientras este sigue dentro del huevo: tutorial). 
 	A lo largo de su aventura nuestro protagonista pasa por diversos biomas en busca del libro de la genética animal persiguiendo a Salomón el salmón que había robado el libro el libro para cambiar su genética para poder volar, ya que este no era capaz de escalar la cascada que escalaban todos los de su especie por lo cual le discriminan y marginan. Ese día se cansó y fue en busca del libro; lo robó y cambió su genética. 
 	El primer bioma al que se enfrenta Flash es la jungla, su hábitat con los leopardos. Por el camino mientras persigue a Salomón se da cuenta de que este estaba modificando la genética de los animales que se encontraban traba para evitar así que Flash le alcanzara. En este bioma encuentra monos con 4 brazos, serpientes con patas, rinocerontes a dos patas y como jefe del hábitat un gran elefante luchador a dos patas. 
 	El siguiente bioma por el que pasa Salomón en su huida es el desértico donde nuestro protagonista encontrará diversos animales cada vez más peligrosos, entre ellos camellos tácticos, escorpiones con 2 colas que disparan veneno, avestruces con pinchos y como boss de la zona un canguro boxeador. 
Continuando con la persecución pasan por un bioma gélido donde encuentran animales como osos polares resfriados, narvales con pulmones y pingüinos, muchos pingüinos, voladores y el boss… más pingüinos, muchos pingüinos, demasiados. 
 	Por la última zona por la que pasan en esta persecución es la playa donde encontraran una gran cantidad de animales muy molestos tales como tortugas sin caparazón, cangrejos con 6 pinzas, gaviotas que escupen conchas afiladas que se clavan en la arena, pelícanos con 2 picos y como boss un pulpo gigante con muchos tentáculos.  
 	En el final de su huida, siguiendo el flujo del río llegan a la cascada donde habita Salomón, pero antes de llegar, Flash se da cuenta de que  Salomón se había llevado animales de todos los biomas y le atacaran todos antes de alcanzar a Salomón. 
 	La batalla final será un encarnizado combate entre Flash y Salomón por el control del libro. 
 	Al derrotar a Salomón y recuperar el libro se restablece la genética de todos los animales modificados por Salomón incluyendo a este, pero gracias a las fuerzas conseguidas en el combate Salomón ya es capaz de escalar la cascada sin necesidad de tener alas.  
 	Además de esto Flash modifica la genética de los de su especie y les hace más rápidos, en cambio para el que ya era rápido se convierte en ninja

**Comment by iuvissito** [comment]
Lema :  ¿¡Perezoso, el más veloz?!  ¡¡¡¡¡Error 404!!!!

me confundí y borre el que habías hecho del lema jairo,lo vuelvo a subir

**Comment by iuvissito** [comment]
Una familia de leopardos se encuentran un huevo,el cual se había caído del árbol en el que estaba ,debido a las fuertes tormentas que habían tenido lugar los días anteriores,los leopardos decidieron llevarse el huevo y cuidarlo como un hijo ,ias más tarde el huevo se rompe,saliendo de ahi ,un perezoso,cuyo nombre seria Flash.

Flash creció pensando que era uno más de la familia , más tarde se daría cuenta que sus padres ,  no eran sus padres,por lo que empezaria a buscar a su verdadera especie ,cuando la encontró se llevó un gran chasco su especie ,era lenta , y se pasaba la mayoría del día durmiendo,lo que explicaba el porque no conseguía ser tan rápido como sus hermanos ,Flash supo desde ese momento que tenía que hacer algo para cambiarlo,por lo que emprendería su búsqueda, en esta búsqueda encontraría la solución a sus problemas ,un libro llamado,el Libro de la genética,con este libro podría hacer que su sueño se hiciese realidad por lo que una vez fijado su objetivo se lanza a la aventura para encontrarlo.

En su aventura se encuentra como varios animales se interponen en su paso,según va avanzando descubre que estos ataques no son fortuitos,si no que se deben a que el dueño del libro ,Salomón, se los manda para evitar que este le arrebate el poder que tiene sobre el mundo animal, a cada paso ,se le va haciendo más complicado avanzar debido a sus propias limitación ,para conseguir superarlas deberá adentrarse en el camino ninja para poder obtener la fuerza necesaria para sobreponerse a la  situación y lograr poner sus zarpas sobre el ansiado libro de la genética.

Según va viendo su objetivo mas cerca se entera de que su enemigo tuvo que ver ,en que sea como es ,que naciera de un huevo y sea veloz ,aparte del hecho de haberse criado con una familia de leopardos,por lo que se instauraron unas dudas que debe resolver mientras sigue su camino.

**Comment by iuvissito** [comment]
Plot points: 
Flash descubre que no es un leopardo como sus padres adoptivos ,si no que es un perezoso 
Al crecer Flash descubre que los perezosos, su especie, no son rápidos como él, decide emprender una aventura ,para cambiar este hecho
-Descubre que los enemigos que le quieren impedir realizar el cambio estno lean comandados por Salomón ,quien posee el libro de la genética y que para lograr su objetivo ,no le basta con sus habilidades ,deberá mejorarlas convirtiéndose en un gran ninja

-Sufre la mayor revelación ¡¡¡ Salomón es el culpable de que sea como es!!! en sus cambios en el libro hizo uno ya sea directa o indirectamente por lo que provoco que Flash naciera de un huevo ,y fuera algo más veloz que los demás perezosos
