### ISSUE TITLE
Niveles

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#6]

**Comment by Apodomorata** [comment]
2.4 Niveles
A lo largo del juego, nuestro protagonista, irá pasando por una serie de niveles, cada uno ambientado en un  bioma diferente.
Primer Nivel: La Selva
Estará separado en varias fases:
1º Tutorial: en esta fase se le enseñará al jugador las mecánicas básicas mediante una serie de dibujos ( se intentará evitar el texto para que sea más dinámico)
2º Fase: el jugador a partir de aquí podrá moverse libremente por el mapa, es una fase de adaptación, y empezará a encontrarse con enemigos. A lo largo de esta fase, habrá objetos poco escondidos para que el jugador descubra que hay objetos y fomentar la exploración.
3º Fase: el jugador entra en un templo, en él tendrá que seguir avanzando, investigando y tendrá que resolver un puzzle para poder abrir una puerta. Al ser el primer nivel, será un puzzle muy fácil, tendrá que investigar el mapa para activar unas palancas para abrir la puerta.
4º Fase: esta fase se desarrolla en una habitación amplia, en ella deberá enfrentarse a un jefe final del primer nivel.
Escenario Jungla:





Segundo Nivel: Desierto
Al cambiar de nivel, y de bioma, la ambientación del nivel cambia también
El segundo nivel está basado en un bioma de desierto. El nivel también estará dividido en: una fase de adaptación a los enemigos, otra de combate, un  puzzle y una pelea contra el jefe del desierto.Escenario del desierto:
Tercer Nivel: La Playa
Nivel que se desarrolla en un escenario de playa, como en los demás niveles, este estará dividido en diferentes fases de dificultad ascendente. También habrá un puzzle con una dificultad mayor y el jefe también será más difícil de derrotar.
Cuarto nivel: Final
Nivel final en el que aparecerám todos los enemigos que han aparecido en el jugo y en el que tendrás que enfrentarte al jefe final: Salomón el salmón.

**Comment by Apodomorata** [comment]
![IMG_2507](https://user-images.githubusercontent.com/91078700/141212597-27349632-11e9-40a6-82ce-ead9ae610d1d.JPG)
![IMG_2501](https://user-images.githubusercontent.com/91078700/141212600-44d78fac-4daa-4491-bd13-c7c10880a5d7.JPG)
![IMG_2502](https://user-images.githubusercontent.com/91078700/141212601-46a65daa-5613-443b-81db-d96207e68a85.JPG)
![IMG_2503](https://user-images.githubusercontent.com/91078700/141212603-5e62172d-c326-46a1-a0ef-d9aa9e8c19c7.JPG)
![IMG_2504](https://user-images.githubusercontent.com/91078700/141212605-f7ed1668-84d9-404c-a7f1-483270e1a1dd.JPG)
![IMG_2506](https://user-images.githubusercontent.com/91078700/141212606-911f5f0d-7a48-483c-9ce1-72386d05feef.JPG)
![IMG_2505](https://user-images.githubusercontent.com/91078700/141212607-36377469-cf53-4e07-81fa-2e69174d105d.JPG)
![IMG_2509](https://user-images.githubusercontent.com/91078700/141212608-930ff3c5-3468-454c-b261-9b67cdfe9cb0.JPG)
![IMG_2510](https://user-images.githubusercontent.com/91078700/141212610-032d590c-78b9-41d3-b87a-972bfdd5e309.JPG)
![IMG_2511](https://user-images.githubusercontent.com/91078700/141212611-565f7bc1-a959-4c36-a3b6-bcebde5d19d5.JPG)
![IMG_2512](https://user-images.githubusercontent.com/91078700/141212613-d388f0c4-fbaa-46af-8aae-d3dfe2315b02.JPG)
![IMG_2513](https://user-images.githubusercontent.com/91078700/141212615-cbd4f535-a08a-41b9-8bd9-7b45e91f6725.JPG)
![IMG_2514](https://user-images.githubusercontent.com/91078700/141212617-2e815b9c-85e5-4cd5-9001-1e17cc5976ab.JPG)
![IMG_2515](https://user-images.githubusercontent.com/91078700/141212619-68a4d033-baf7-4769-9683-9ee517e5489b.JPG)
![IMG_2508](https://user-images.githubusercontent.com/91078700/141212620-e45d8b6f-cdad-46a3-b21f-7321aa2008a2.JPG)

**Comment by Apodomorata** [comment]
No me había dado tiempo a subir las imágenes en clase
