### ISSUE TITLE
Público objetivo

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#7]

**Comment by vilkiin** [comment]
Público objetivo:
Al ser un juego de estilo cartoon, trata sobre un perezoso y sus aventuras y cuya dificultad no es muy alta. Pensamos en que este juego sería para un público casual partiendo desde los siete años. Pero claramente cualquiera podría jugarlo. Además, tiene una estética limpia y divertida con un humor sarcástico e ingenioso sobre los animales.
