### ISSUE TITLE
Jugabilidad

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#8]
Mecánicas
Habilidades
4 elementos
Sistema de vidas
Objetos

**Comment by Apodomorata** [comment]
UGABILIDAD
Este juego es un 2,5D de plataformas que se desarrolla en un entorno 3D en el que se verá un gran plano general, picado y de perfil, del jugador, con una cámara que le seguirá a lo largo del mapa.
Se tendrá una serie de mecánicas clásicas, y a lo largo de la aventura irás obteniendo diferentes mecánicas para poder seguir avanzando en la historia.

**Comment by Apodomorata** [comment]
Mecánicas básicas: las imprescindibles en un juego de plataformas. 
Desplazamiento lateral
Salto
Ataque básico.

**Comment by Apodomorata** [comment]
Mecánicas avanzadas: a lo largo de la historia el jugador irá obteniendo mecánicas más avanzadas y acorde con la dificultad de los niveles. De esta manera la dificultad del gameplay irá avanzando a la vez que la historia, pero sin ser demasiado difícil, para que siga siendo un juego casual. 
Doble salto
Agarre a las paredes
 Dash
Combos de golpes:
Abajo + golpe básico = Derribar al rival
Salto + golpe básico = Golpe en caída (Con más potencia)

**Comment by Apodomorata** [comment]
Habilidades

A lo largo de la partida el perezoso podrá hacer uso de distintos elementos naturales (agua, fuego, tierra, viento), cada elemento dispondrá de una serie de habilidades que podrá utilizar el jugador, tendrán un tiempo de reutilización (cooldown).

Cada elemento tendrá 3 habilidades:
Disparo del elemento.
Una habilidad personalizada por cada elemento.
Una habilidad definitiva que tendrá un tiempo de reutilización mayor, pero que a su vez tendrá mucho más impacto.

**Comment by Apodomorata** [comment]
4 Elementos

Al tratarse de un perezoso ninja puede manejar 4 elementos naturales, el cual cada uno de ellos le proporciona unas habilidades especiales.

Cuando el perezoso lleva uno de los elementos activados, sus ataques básicos, sus mecánicas y habilidades, cambian su aspecto al elemento correspondiente y también cambia alguna de sus estadísticas para cambiar un poco la dinámica de juego y el uso que se deba usar para ese elemento.
Agua: 

Pasiva: cada vez que recibes daño te curas un pequeño porcentaje del daño que te hacen.
Cada tercer ataque básico se cura un un pequeño porcentaje de vida.
1º habilidad: lanza una esfera de agua que si impacta causa daño y cura una parte del daño.
2º habilidad: se generan dos cadenas que alcanza a los enemigos más cercanos y dos segundos después les aturde.
3º habilidad: genera una gran ola que aturde a los enemigos alcanzados.

Fuego:

Pasiva: cada vez que recibes daño, provocas un quemado en el enemigo a lo largo del tiempo. 
Sus ataques básicos producen un pequeño efecto de quemado en los enemigos.
1º habilidad: lanza una bola de fuego que al alcanzar al enemigo explota, causa daño y golpea también enemigos adyacentes.
2º habilidad: lanza una hilera de ascuas que generan una zona en la que a los enemigos que están encima sufren un daño por quemado.
3º habilidad: lanza una serie de bolas de fuego al cielo, que al caer explotan y provocan un gran daño en el área.

Tierra:

Pasiva: si pasan 3 segundos sin recibir daño, se genera un escudo de 20 de vida.
El primer ataque básico a cada enemigo provoca un pequeño aturdimiento.
1º habilidad: lanza una roca que causa daño y aturde al enemigo.
2º habilidad: salta y al caer golpea el suelo, haciendo un golpe en área que derriba a los enemigos.
3º habilidad: se genera una especie de golem de piedra, que solamente avanza, y provoca a los enemigos haciendo que le golpeen. 

Aire: 

Pasiva: te mueves un poco más rápido y las mecánicas de desplazamiento se hacen más efectivas.
Si realiza dos ataques básicos a un mismo objetivo este se ve arrastrado hacia atrás.
1º habilidad: lanza una esfera de aire que causa daño y hace retroceder al enemigo.
2º habilidad: genera una gran ola de aire, que hace retroceder mucho a los enemigos y salta hacia atrás.
3º habilidad: realiza un salto muy alto del que desciende lentamente y genera una serie de remolinos debajo que causan daño a los enemigos y los deja derribados.

**Comment by Apodomorata** [comment]
Sistema de vidas

El jugador dispondrá de una barra de vida, que estará puesta en la UI, de 100 puntos de vida. Se irán perdiendo puntos de vida cuando los enemigos golpeen al jugador. Cada enemigo tendrá unas habilidades y unas estadísticas diferentes. 
La vida se podrá restaurar mediante habilidades o utilizando objetos.

**Comment by Apodomorata** [comment]
Objetos

A lo largo del mapa podrás encontrar distintos cofres con consumibles de distintos tipos.
En la UI habrá un slot para utilizarlos.
Fruta: Te cura 20 puntos de salud.
Granada: Se lanza y causa daño en el área.
Fruta enredadera: Se lanza y causa un área en el suelo que atrapa a los enemigos por unos segundos.
Fruta de velocidad: Al consumirla te proporciona movilidad extra.
