### ISSUE TITLE
Jefes

### ISSUE THREAD

**Issue by Jairop310** [CIFP-Jose-luis-Garci/LazyClawns#9]

**Comment by vilkiin** [comment]
Jefes:
-Jungla:
![Elefante](https://user-images.githubusercontent.com/79110145/140827278-9a4782fa-fa39-427a-8410-b3b27a6fdb88.png)

Este es el jefe del bioma de jungla, por lo tanto, el más fuerte. El gran elefante posee buenas dotes de combate cuerpo a cuerpo, pero además tiene una gran habilidad definitiva, lanzar potentes chorros de agua por las trompas, más te vale esquivarlos.

-Desierto:
![Canguro](https://user-images.githubusercontent.com/79110145/140827356-5b732227-a900-4dbc-93d6-face47f21994.png)

¿Bueno muy típico eso de los canguros boxeadores no? pero hum... si este es el boss es por algo, este es muy ágil y fuerte y además cuidado con su cría ya que este intentara lanzarla a tus espaldas en cuanto te descuides y si te rodean te lloverán puñetazos por todos lados y créeme caerás K.O. en menos de un round.
